export const THUMBNAIL_SLOT_SIZE = 56;
export const THUMBNAIL_SLOT_PADDING = 4;
export const THUMBNAIL_INNER_SIZE = THUMBNAIL_SLOT_SIZE - THUMBNAIL_SLOT_PADDING * 2; // 48
export const THUMBNAIL_RENDER_SCALE = 2;
